[package]
name = "mini_gtfs_rs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
name = "mini_gtfs_rs"
crate-type = ["cdylib"]

[dependencies]
pyo3 = "0.22.0"
csv = "1.3.0"
serde = { version = "1.0.209", features = ["derive"] }
